require("core.tweaks.telescope")
require("core.tweaks.completions")
require("core.tweaks.lsp_config")
require("core.tweaks.lualine")
require("core.tweaks.colorscheme")
require("core.tweaks.conform")
require("core.tweaks.mason")
require("core.tweaks.toggleterminal")
